import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/navBar";

export const metadata: Metadata = {
  title: "Macbook Style Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
