import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/navBar";
import { Dock } from "@/components/dock";

export const metadata: Metadata = {
  title: "Macbook Style Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <main>
          <NavBar />
          {children}
          <Dock />
        </main>
      </body>
    </html>
  );
}
